version: "1"
services:
  - type: web
    name: challengehub
    runtime: python
    plan: free
    branch: main
    autoDeploy: true
    
    pythonVersion: "3.11.0"
    
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
      python manage.py migrate --noinput
            
      # Собираем статические файлы
      python manage.py collectstatic --noinput
    
    startCommand: gunicorn challengehub.wsgi:application
    
    envVars:
      - key: PYTHON_VERSION
        value: "3.11.0"
      - key: DJANGO_SETTINGS_MODULE
        value: challengehub.settings
      - key: DEBUG
        value: "false"
      - key: SECRET_KEY
        sync: false
        generateValue: true
      - key: ALLOWED_HOSTS
        value: ".onrender.com"
      - key: DISABLE_COLLECTSTATIC
        value: "0"
    
    disk:
      name: data
      mountPath: /opt/render/project/data
      sizeGB: 1